#####
# Smithed Library Template
# 
# -> Replace `[...]` with your pack details
#####

# General Pack Details
id: 'smithed.[pack_id]'  # smithed.name
name: '[Pack Name]'
description: '[Pack Description]'
version: '0.0.1'

# Data Pack Configuration (if using data pack)
data_pack:
  load: .
  render:
    functions: smithed.[pack_id]:*
      
# Resource Pack Configuration (if using resource pack)
resource_pack:
  load: .

# Plugins that run before pack is loaded
require:
  - bolt   # Optional (omit if not using `bolt`)

# Plugins that run after pack is loaded
pipeline:
  - mecha  # Validates commands (and executes custom commands such as `bolt`) 

# Extra values to configure plugins, etc
meta:
  # Used to version pack for release
  versioning:
    scoreholder: '#smithed.[pack_id]'
    namespace: smithed.[pack_id]

  # Used to indicate to LL what the main file
  scheduled: [tick]
