pipeline:
  - extend: beet.yaml
    pipeline: [smithed_libraries.plugins.misc.output_dist]
  - smithed_libraries.plugins.manifest.output_version_manifest

meta:
  # Disabling the "meta.autosave.link" option makes it so
  #  that if we have a "$ beet link" set up for development
  #  we won't pollute the "datapacks" directory with the
  #  release files.
  autosave:
    link: false
