author: Smithed Council

output: ../../../dist

require:
  - smithed_libraries.plugins.relay_config
  - smithed_libraries.plugins.versioning
  - smithed_libraries.plugins.documentation

pipeline:
  - mecha

meta:
  zip: false  # sets both data_pack and resource_pack zipped

  mecha:
    formatting: preserve

  replace_version:  
    - "{{ ctx.project_id }}:impl/": "{{ ctx.project_id }}:impl/{{ version }}"
