name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install mecha and beet
      run: 'pip install -U beet mecha bolt bolt-expressions'
    - name: Build
      run: 'beet'
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: packs
        path: dist/*.zip
