name: Build Nightly Libraries

on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    #----------------------------------------------
    #       check-out repo and set-up python
    #----------------------------------------------
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    #----------------------------------------------
    #  -----  install & configure poetry  -----
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: '1.2.2'
        virtualenvs-in-project: true

    #----------------------------------------------
    #       load cached venv if cache exists
    #----------------------------------------------
    - name: Setup cache
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

    #----------------------------------------------
    # install dependencies if cache does not exist
    #----------------------------------------------
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install
    
    #----------------------------------------------
    #          Build libraries via beet
    #----------------------------------------------
    - name: Build via beet
      run: poetry run beet -s "data_pack.zipped = true" -s "resource_pack.zipped = true"

    #----------------------------------------------
    #           Upload artifacts to GH
    #----------------------------------------------
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: packs
        path: dist/*.zip
