name: Release Packages

on: 
  push:
    branches:
      - main
    paths:
      - smithed_libraries/packs/*
      - pyproject.toml

  workflow_dispatch:

env:
  MC_VERSION: '1.19'
  COMMIT_MSG: ${{ github.event.head_commit.message }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:

    #----------------------------------------------
    #            Setup Build Environment
    #----------------------------------------------

    - name: Checkout 'main'
      uses: actions/checkout@v3
      with:
        path: 'libraries'
        fetch-depth: 0

    - name: Checkout 'releases'
      uses: actions/checkout@v3
      with:
        path: 'releases'
        ref: 'releases'
        fetch-depth: 0
    
    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
        cache-dependency-path: |
          libraries/poetry.lock

    #----------------------------------------------
    #  -----  install & configure poetry  -----
    #----------------------------------------------

    - name: Install dependencies
      run: |
        cd libraries
        poetry install --with dev

    #----------------------------------------------
    #       Build packs and copy to branch
    #----------------------------------------------
    
    - id: beet-build
      name: Build via Beet
      run: | 
        cd libraries
        mkdir -p dist
        cp ../releases/$MC_VERSION/manifest.json dist/manifest.json
        poetry run python .github/workflows/build-changes.py

    #----------------------------------------------
    #                 Push to PYPI
    #----------------------------------------------

    - id: pypi_release
      name: Release for PYPI
      if: github.repository == 'Smithed-MC/Libraries'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        cd libraries
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        poetry run semantic-release publish -v DEBUG -D commit_author="github-actions <action@github.com>"
    
    #----------------------------------------------
    #        Commit built packs to branch
    #----------------------------------------------
    #  We use `&&` to ensure git steps are atomic
    #  TODO: Fix `git commit` message line
    #----------------------------------------------

    - name: Copy and push release files to branch
      if: steps.beet-build.outputs.build_changes
      run: |
        set -e
        mkdir -p releases/$MC_VERSION
        cp -rf libraries/dist/* releases/$MC_VERSION
        cd releases
        SHORT_HASH=$(git rev-parse --short HEAD)
        VERSION=$(poetry run semantic-release print-version)
        git add .
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        git commit -m "🚀 $SHORT_HASH (v$VERSION): $COMMIT_MSG"
        git push --force origin releases
