name: Release Packages

on:
  - workflow_dispatch

env:
  MC_VERSION: '1.19'
  COMMIT_MSG: ${{ github.event.head_commit.message }}

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:

    #----------------------------------------------
    #            Setup Build Environment
    #----------------------------------------------

    - name: Checkout 'main'
      uses: actions/checkout@v3
      with:
        path: 'libraries'

    - name: Checkout 'releases'
      uses: actions/checkout@v3
      with:
        path: 'releases'
        ref: 'releases'
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: '1.2.2'
        virtualenvs-in-project: true

    - name: Setup cache
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies (skip if cached)
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install

    #----------------------------------------------
    #       Build packs and copy to branch
    #----------------------------------------------
    
    - name: Build via Beet
      run: |
        poetry run beet -p libraries/beet-release.yaml

    - name: Copy files to releases
      run: |
        mkdir releases/$MC_VERSION
        cp -rf ../libraries/dist/* releases/$MC_VERSION

    #----------------------------------------------
    #                 Push to PYPI
    #----------------------------------------------

    - name: Release for PYPI
      if: |
        github.repository == 'SmithedMC/smithed_libraries'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        cd libraries
        VERSION=$(semantic-release print-version)
        poetry run semantic-release publish -v DEBUG -D commit_author="github-actions <action@github.com>"
    
    #----------------------------------------------
    #        Commit built packs to branch
    #----------------------------------------------
    #  We use `&&` to ensure git steps are atomic
    #----------------------------------------------

    - name: Copy files to releases
      run: |
        set -e
        cd releases
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        git add .
        git commit -m "🚀 {{ github.event.after }} (v$VERSION): $COMMIT_MSG"
        git push --force origin releases
