name: Release Packages

on:
  workflow_dispatch:
    inputs:
      libraries:
        description: 'List of libraries to release'
        default: 'meta.libraries = []'
        type: string
        required: false


jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install mecha and beet
      run: "pip install -U beet mecha bolt 'bolt-expressions>=0.6.1'"
    - name: Checkout 'main'
      uses: actions/checkout@v3
      with:
        path: 'libraries'
    - name: Checkout 'releases'
      uses: actions/checkout@v3
      with:
        path: 'releases'
        ref: 'releases'
    - name: Build via Beet
      run:
      - 'cd libraries'
      - beet -s "meta.release = True" -s "${{ inputs.libraries }}"
      - 'cd ..'
    - name: Copy files to releases
      run:
      - 'cd releases'
      - 'cp -rf ../libraries/dist/* .'
      - 'cp ../libraries/latest.yaml latest.yaml'
      - 'git add . && git commit -m "Update libraries" && git push origin releases'
